name: deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:  
  commitUpdate:
    name: Update version & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set version env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      # ref: https://stackoverflow.com/questions/65606498/how-to-access-github-tag-message-in-github-actions
      - name: Get and set tag message
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/}
          echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
      
      - name: Test env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $TAG_VERSION
          echo ${{ env.TAG_VERSION }}
          echo ${{ env.TAG_MESSAGE }}