name: deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:  
  commitUpdate:
    name: Update version & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set version env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "TAG_VERSION=${RELEASE_VERSION:1}" >> $GITHUB_ENV
      - name: Test env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $TAG_VERSION
          echo ${{ env.TAG_VERSION }}